Controllers/TblOrdersCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerMaster.Models;
using CustomerMaster.ViewModels;
using CustomerMaster.Util;
using Microsoft.AspNetCore.Authorization;

namespace CustomerMaster.Controllers
{
    ////[Authorize(Policy = "RequireCMViewRole")]
    public class TblOrdersCommentsController : Controller
    {
        private readonly CustomerMasterContext _context;

        public TblOrdersCommentsController(CustomerMasterContext context)
        {
            _context = context;
        }

        // GET: TblOrdersComments
        public async Task<IActionResult> Index(
            string sortOrder,
            int? companyIdFilter, int? acctNumberFilter, int? tblDbCustomersShipToIdFilter,
            string custNameContainsFilter,
            int? companyIdSearch, int? acctNumberSearch, int? tblDbCustomersShipToIdSearch,
            string custNameContainsSearch,
            int? pageNumber
        )
        {
            ViewData["CreatedDateSortParm"] = string.IsNullOrEmpty(sortOrder) ? "createdDate_desc" : "";
            ViewData["AcctNumberSortParm"] = sortOrder == "AcctNumber" ? "acctNumber_desc" : "AcctNumber";

            if (
                companyIdSearch != null || acctNumberSearch != null
                ||
                tblDbCustomersShipToIdSearch != null
                ||
                custNameContainsSearch != null
            )
            {
                pageNumber = 1;
            }
            else
            {
                companyIdSearch = companyIdFilter;
                acctNumberSearch = acctNumberFilter;
                tblDbCustomersShipToIdSearch = tblDbCustomersShipToIdFilter;
                custNameContainsSearch = custNameContainsFilter;
            }

            ViewData["CompanyIdFilter"] = companyIdSearch;
            PopulateCompanyIdDropDown();

            ViewData["AcctNumberFilter"] = acctNumberSearch;
            PopulateAcctNumberDropDown(companyIdSearch);

            ViewData["TblDbCustomersShipToIdFilter"] = tblDbCustomersShipToIdSearch;
            PopulateTblDbCustomersShipToDropDown(companyIdSearch, acctNumberSearch);

            ViewData["CustNameContainsFilter"] = custNameContainsSearch;

            var someFieldCollection =
                (
                    from s in _context.TblOrdersComments
                    join ship in _context.TblDbCustomersShipTo
                        on
                            new { s.CompanyId, s.AcctNumber, s.CustId }
                            equals
                            new { ship.CompanyId, ship.AcctNumber, ship.CustId }
                    where
                        ship.Deleted == false && ship.CustShipName != null && ship.CustShipActive == -1
                    join cust in _context.TblDbCustomers
                        on
                            new { ship.CompanyId, AcctNumber = (ship.AcctNumber ?? 0) }
                            equals
                            new { cust.CompanyId, cust.AcctNumber }
                    where
                        cust.Deleted == false && cust.CustActive == -1
                        &&
                        (
                            string.IsNullOrEmpty(custNameContainsSearch)
                            ||
                            (
                                !string.IsNullOrEmpty(custNameContainsSearch)
                                &&
                                cust.CustName.Contains(custNameContainsSearch)
                            )
                        )
                        &&
                        (cust.CompanyId == 1 || cust.CompanyId == 2 || cust.CompanyId == 4)
                    join rep in _context.TblOrdersInsideRep
                        on
                            new { Initials = cust.InsideRep, Company = cust.CompanyId.ToString(), cust.Deleted }
                            equals
                            new { rep.Initials, rep.Company, rep.Deleted } into pp1
                    from rep in pp1.DefaultIfEmpty()
                    join rep1 in _context.TblOrdersOutsideRep
                        on
                            new { Initials = cust.OutsideRep, cust.CompanyId, cust.Deleted }
                            equals
                            new { rep1.Initials, rep1.CompanyId, rep1.Deleted } into pp2
                    from rep1 in pp2.DefaultIfEmpty()
                    join reps in _context.TblOrdersInsideRep
                        on
                            new { Initials = ship.InsideRep, Company = ship.CompanyId.ToString(), ship.Deleted }
                            equals
                            new { reps.Initials, reps.Company, reps.Deleted } into pp1s
                    from reps in pp1s.DefaultIfEmpty()
                    join rep1s in _context.TblOrdersOutsideRep
                        on
                            new { Initials = ship.OutsideRep, ship.CompanyId, ship.Deleted }
                            equals
                            new { rep1s.Initials, rep1s.CompanyId, rep1s.Deleted } into pp2s
                    from rep1s in pp2s.DefaultIfEmpty()
                    select new CustomerMaster.ViewModels.VwOrdersComments
                    {
                        Id = s.Id,
                        Comment = s.Comment,
                        CreatedDate = s.CreatedDate,
                        CompanyId = s.CompanyId,
                        CreatedUser = s.CreatedUser,
                        CreatedWorkStation = s.CreatedWorkStation,
                        AcctNumber = s.AcctNumber,
                        CustId = s.CustId,
                        UpdatedUser = s.UpdatedUser,
                        UpdatedDateTime = s.UpdatedDateTime,
                        BillCustAlpha = cust.CustAlpha,
                        BillCustName = cust.CustName,
                        CustBillAddress = cust.CustBillAddress,
                        CustBillAddr2 = cust.CustBillAddr2,
                        CustBillCity = cust.CustBillCity,
                        CustBillState = cust.CustBillState,
                        CustBillZipCode = cust.CustBillZipCode,
                        CustBillActive = (cust.CustActive == -1 ? true : false),
                        CustBillContact = cust.CustContact,
                        CustBillPlant = cust.CustPlant,
                        CustBillPhone = cust.CustPhone,
                        CustBillFax = cust.CustFax,
                        BillInsideRep = rep.RepName,
                        BillOutsideRep = rep1.RepName,
                        BillCustomerTerms = cust.CustomerTerms,
                        BillAllowedOverRunPercentage = cust.AllowedOverRunPercentage,
                        BillToEmailAddress = cust.BillToEmailAddress,
                        BillMasterAcctNumber = cust.MasterAcctNumber,
                        BillUpdatedUser = cust.UpdatedUser,
                        BillUpdatedDateTime = cust.UpdatedDateTime,
                        ShipToSameAsBillTo = (cust.ShipToCheck == -1 ? true : false),
                        TblDbCustomersShipToId = ship.Id,
                        ShipCustActive = (ship.CustShipActive == -1 ? true : false),
                        ShipCustAlpha = ship.CustAlpha,
                        CustShipName = ship.CustShipName,
                        CustShipAddress = ship.CustShipAddress,
                        CustShipAddr2 = ship.CustShipAddr2,
                        CustShipCity = ship.CustShipCity,
                        CustShipState = ship.CustShipState,
                        CustShipZipCode = ship.CustShipZipCode,
                        CustShipContact = ship.CustContact,
                        CustShipPlant = ship.CustPlant,
                        CustShipPhone = ship.CustPhone,
                        CustShipFax = ship.CustFax,
                        ShipInsideRep = reps.RepName,
                        ShipOutsideRep = rep1s.RepName,
                        ShipUpdatedUser = ship.UpdatedUser,
                        ShipUpdatedDateTime = ship.UpdatedDateTime
                    }
                );
            IQueryable<CustomerMaster.ViewModels.VwOrdersComments> fields =
                someFieldCollection.Cast<CustomerMaster.ViewModels.VwOrdersComments>();

            var someFieldCollection1 =
                (
                    from ship in _context.TblDbCustomersShipTo
                    join cust in _context.TblDbCustomers
                        on
                            new { ship.CompanyId, AcctNumber = (ship.AcctNumber ?? 0) }
                            equals
                            new { cust.CompanyId, cust.AcctNumber }
                    where
                        ship.Deleted == false && ship.CustShipName != null
                        &&
                        ship.CustShipActive == -1
                        &&
                        cust.Deleted == false && cust.CustActive == -1
                        &&
                        (
                            string.IsNullOrEmpty(custNameContainsSearch)
                            ||
                            (
                                !string.IsNullOrEmpty(custNameContainsSearch)
                                &&
                                cust.CustName.Contains(custNameContainsSearch)
                            )
                        )
                        &&
                        (cust.CompanyId == 1 || cust.CompanyId == 2 || cust.CompanyId == 4)
                    join comm in _context.TblOrdersComments
                        on
                            new { ship.CompanyId, ship.AcctNumber, ship.CustId }
                            equals
                            new { comm.CompanyId, comm.AcctNumber, comm.CustId }

Views/Shared/_Layout.cshtml
@{
    string mySQLServer = Environment.GetEnvironmentVariable("ASPNETCORE_SQLSERVER");
    var myEnv = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
    string myLogoHeading = "Customer Master";
    if (mySQLServer.ToLower() == "vmsql001")
    {
        myLogoHeading += "(Azure) - ";
    }
    else
    {
        myLogoHeading += "(Local) - ";
    }
    if (myEnv.ToLower().Contains("development"))
    {
        myLogoHeading += "DEV";
    }
    else if (myEnv.ToLower().Contains("staging"))
    {
        myLogoHeading += "STG";
    }
    else
    {
        myLogoHeading += "PROD";
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Customer Master</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"
                   style="color: @Environment.GetEnvironmentVariable("ASPNETCORE_PLATFORM_COLOR")">

                    @myLogoHeading
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TblOrdersComments" asp-action="Index">Shipping Comments</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Customer Master
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>